version: '3'

networks:
  um-network:
    driver: bridge

services:
  client:
    container_name: um-client
    restart: always
    build: ./client
    ports:
      - 80:8080
    networks:
      - um-network

  server:
    container_name: um-server
    restart: always
    build: ./server
    ports:
      - 5000:5000
    networks:
      - um-network
